version: '3'
services:
  tmodloader:
    image: 'jacobsmile/tmodloader1.4'
    container_name: 'tmodloader'
    ports:
      - "7777:7777"
    expose:
      - "7777"
    environment:
      # Download these mods:F
      #CALAMITY=2824688072
      #CALAMITY_MUSIC=2824688266
      #RECIPE_BROWSER=2619954303
      #MAGIC_STORAGE=2563309347
      #HELPFUL_HOTKEYS=2645058109
      #BOSS_CHECKLIST=2669644269
      #EXPANDED_INVENTORY=2925134686
      - "TMOD_AUTODOWNLOAD=2824688072,2824688266,2619954303,2563309347,2925134686,2669644269,2645058109"
      # Enable mods.
      - "TMOD_ENABLEDMODS=2824688072,2824688266,2619954303,2563309347,2925134686,2669644269,2645058109"
      # Shutdown Message and Autosave Interval (In Minutes)
      - "TMOD_SHUTDOWN_MESSAGE=Server is shutting down..."
      - "TMOD_AUTOSAVE_INTERVAL=10"
      # Server Settings
      - "TMOD_MOTD=Welcome to Simtat 3"
      - "TMOD_PASS=xband"
      - "TMOD_MAXPLAYERS=16"
      - "TMOD_WORLDNAME=Simtat3"
      - "TMOD_WORLDSIZE=3"
      - "TMOD_WORLDSEED="
      # If set to "Yes", it is expected to have a config.txt mapped. The Server Settings above will be ignored.
      - "TMOD_USECONFIGFILE=No"
      - "TMOD_WORKSHOP=/root/terraria-server/workshop-mods"
      - "TMOD_WORLDS=/root/.local/share/Terraria/tModLoader/Worlds"

    volumes:
      - "/path/to/worlds/file:/root/.local/share/Terraria/tModLoader/Worlds"
      - "/path/to/workshop/folder:/root/terraria-server/workshop-mods"
